# Generated by Django 5.2.8 on 2026-02-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('croppilot_app', '0002_diseasereport_confidence_alter_agricultureofficer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerquery',
            name='officer',
        ),
        migrations.AddField(
            model_name='farmerquery',
            name='replied',
            field=models.BooleanField(default=False),
        ),
    ]
