# Generated by Django 5.2.8 on 2026-02-10 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('croppilot_app', '0003_remove_farmerquery_officer_farmerquery_replied'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='croppilot_app.crop')),
            ],
        ),
        migrations.CreateModel(
            name='SoilRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_type', models.CharField(max_length=100)),
                ('description_en', models.TextField()),
                ('description_ml', models.TextField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='croppilot_app.crop')),
            ],
        ),
    ]
